config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:new, :create, :destroy]
    end
  end
  root "users#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :read, :all
    return unless user.present? # additional permissions for logged in users (they can read their own posts)

    can :read, Post, author_id: user.id
    can :manage, Post, author_id: user.id # only post owners can manage posts
    can :manage, Comment, author_id: user.id # only post owners can manage posts

    return unless user.admin?

    can :manage, :all
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post, counter_cache: :comments_counter
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  after_save :update_comments_count
  after_destroy :update_comments_count

  def update_comments_count
    post.update(comments_counter: post.comments.size)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: 'User'

  after_save :update_like_counter

  def update_like_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: { maximum: 250 }
  validates_numericality_of :comments_counter, only_integer: true, greater_than_or_equal_to: 0
  validates_numericality_of :likes_counter, only_integer: true, greater_than_or_equal_to: 0

  belongs_to :author, class_name: 'User'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  after_save :update_post_counter

  after_destroy :update_post_counter

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  def update_post_counter
    author.update(postscounter: author.posts.size)
  end

  private

  def set_defaults
    self.comments_counter ||= 0
    self.likes_counter ||= 0
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, format: { with: /[a-zA-Z]/ }
  validates_numericality_of :postscounter, only_integer: true, greater_than_or_equal_to: 0

  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy

  after_initialize :set_defaults

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  def admin?
    # role == requested.role.to_s
    :role == 'admin'
  end

  private

  def set_defaults
    self.postscounter ||= 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  before_action :update_allowed_parameters, if: :devise_controller?

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |field|
      field.permit(:name, :photo, :bio, :postscounter, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.includes(:author_id)
  end

  def show; end

  def new
    @comment = Comment.new
  end

  def create
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id] || params[:id])
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    @comment.post = @post

    respond_to do |format|
      if @comment.save
        format.html do
          redirect_to user_post_url(@user, @post), notice: 'Comment was successfully created.'
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:success] = 'Your comment has been deleted successfully!'
    redirect_to user_post_url(current_user, @comment.post)
  end

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
  end

  def create
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @like = Like.new
    @like.author_id = @user.id
    @like.post_id = @post.id

    respond_to do |format|
      if @like.save
        format.html { redirect_to user_post_url(@user, @post), notice: 'Like was created successfully.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @post = Post.includes(:comments).find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @user = User.find(params[:user_id])
    @post = Post.new(post_params)
    @post.author_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to user_post_url(@user, @post), notice: 'Post was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @user = User.find(@post.author_id)
    @post.destroy
    redirect_to user_url(@user)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text, :comments_counter, :likes_counter)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<span>
  <%= comment.author.name %>: <%= comment.text %>
</span> 

app/views/comments/new.html.erb
<section class="container">
    <%= form_with model: @comment, url: user_post_comments_url, method: :post, local: true do |form| %>
    
      <div class="h-25">
          <%= form.label :Add_New_Comment, "Add New Comment:", class:"form-label" %>
          <%= form.text_area :text, placeholder: "Type your comment here!", rows: 20, required: true,  class: "form-control h-25 d-inline-block" %>        
      </div>

      <div>
          <%= form.submit "Comment", class: "btn btn-primary mt-3" %>
      </div>
    <% end %>
</section>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>
  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogAppRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/likes/new.html.erb
<section class="container">
    <%= form_with(model: @like, url: user_post_likes_path) do |form| %>
    <%= form.submit 'Like this', class: "btn btn-primary" %>
    <% end %>
</section>

app/views/posts/_post.html.erb
<div class="card mt-4 p-4">
 <h2>
    <span>Post #<%=  %></span>
    <span>
      <%= post.title %>
    </span>
  </h2>
   <p>
    <%= post.text %>
  </p>
  <div class="d-flex justify-content-end">
  <small>
    <span>Comment: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></span>
  </small>
  </div>
</div> 

app/views/posts/_post_details.html.erb
<section class="container">
<div class="post">
  <div class="comment-header border p-1">
    <div class="d-flex justify-content-between mb-3">
      <h2>
        Post by <%= link_to post.author.name, user_path(post.author_id) %>
      </h2>
      <small>
        <span>Comment: <%= post.comments_counter %>, Likes: <%= post.likes_counter %></span>
      </small>
      </div>
    <p>
      <%= post.text %>
    </p>
  </div>

</div>
<div class="comments-wrapper border">
  <h3>Comments:</h3>
  <% if @post.comments.empty? %>
    <p>There no comment so far!</p>
  <% end %>
  <% @post.comments.includes([:author]).each do |comment| %>
    <div class="comment-card row">
    <div class="col">
      <strong>
        <%= link_to user_path(comment.author_id) do %>
          <%= comment.author.name %>
        <% end %>
        :
      </strong>
      <%= comment.text %>
      </div>
      <div class="col">
      <% if can? :destroy, comment %>
        <%= button_to 'Delete Comment',  user_post_comment_path(@post.author, @post, comment),  method: :delete, class: "btn text-white btn-danger mt-1 p-1" %>
      <% end %>
      </div>
    </div>
  <% end %>

  <div class="button-user">
    <%= button_to "Add Comment", new_user_post_comment_path(@post.author_id, @post), method: :get, class: "btn btn-primary mt-3" %>
    <%= button_to "Like", new_user_post_like_path(@post.author, @post), method: :get, class: "btn btn-primary mt-3" %>
     <% if can? :destroy, @post %>
        <%= button_to "Delete Post", user_post_path(@post.author, @post), method: :delete, confirm: "Are you sure?", class: "btn btn-primary mt-3" %>
      <% end %>
  </div>
</div>  
</section>
<div class="back-button text-center">
<%= button_to  "Back", user_posts_path(@post.author_id), method: :get, class: "btn btn-primary mt-3 text-center" %>
</div>

app/views/posts/index.html.erb
<%= render partial: "users/user" , locals: { user: @user } %>
<div class="text-center">
  <%= button_to "Share a Post", new_user_post_path(@user.id), method: :get, class: "btn btn-primary mt-3 text-center" %>
</div>
<div class="container">
  <% @posts.each_with_index do |post, index| %>
  <%= link_to user_post_path(@user.id, post.id), class:"text-dark text-decoration-none"  do %>
      <%= render partial: "post" , locals: { post: post, index: index } %>
  <% end %> 
        <ul class="border">
          <% post.comments.includes([:author]).each do |comment| %>
            <li class="list-unstyled">
              <%= render partial: "comments/comment" , locals: { comment: comment } %>
            </li>
            <% end %>
        </ul>
        <% end %>

</div>

app/views/posts/new.html.erb
<h2 class="text-center">Share a new post</h2>

<div class="container">

  <%= form_with model: @post, url: user_posts_path, method: :post, local: true, class:"form" do |form| %>

    <%= form.hidden_field :comments_counter, value: 0 %>
    <%= form.hidden_field :likes_counter, value: 0 %>
    
    <div class="mb-3">
      <%= form.label :title, class:"form-label" %>
      <%= form.text_field :title, class:"form-control", placeholder: "Post title" %>
    </div>

    
    <div class="mb-3">
      <%= form.label :text, class:"form-label" %>
      <%= form.text_area :text, class:"form-control", placeholder: "Content" %>
    </div>

    <%= form.submit :Share, class:"btn btn-primary" %>
  <%end%>
</div>

app/views/posts/show.html.erb
<div>
  <%= render partial: "post_details" , locals: { post: @post } %>
</div>

app/views/users/_user.html.erb
<%= link_to user do %>
<div class="container mt-4">
<div class="card" id="users">
  <div class="row">
    <div class="col-lg-4">
      <%= image_tag('user.png', :alt => "rss feed", class: 'img-fluid rounded-start')   %>
    </div>
    <div class="col-lg-8">
      <h2 class="mt-3">
      <%= user.name %>
    </h2>
    <div class="d-flex w-100 justify-content-end p-3">
    <small>
      Number of posts: <%= user.postscounter %>
    </small>
    </div>

    </div>
  </div>
</div>
</div>
</div>
<% end %> 

app/views/users/index.html.erb
<section class="users-container">  
  <%= render @users %>
</section> 

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>
<div class="container">
  <div class="card mt-4 p-4">
    <h4>Bio</h4>
    <p class="text-muted">
      <%= @user.bio %>
    </p>
  </div>
  <div>
    <% (@user.recent_posts).each do |post, index| %>
      <%= render partial: "posts/post" , locals: { post: post, index: index } %>
    <% end %>
  </div>
  <div class="d-flex flex-column justify-content-center align-items-center mt-3">
    <% if @user.postscounter > 0 %>
      <%= link_to "See all posts" , user_posts_path(@user) %>
    <% else %>
      <h2>No posts for now</h2>
      <div class="text-center">
        <%= button_to "Share a Post", new_user_post_path(@user.id), method: :get, class: "btn btn-primary mt-3 text-center" %>
      </div>
    <% end %>
  </div>
</div>